# Generated by Django 3.1.1 on 2021-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_prenoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fonction',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pays',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
