# Generated by Django 3.1.1 on 2021-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
