# Generated by Django 3.1.1 on 2021-03-23 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_prenoms'),
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travauxdemande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
