# Generated by Django 3.1.1 on 2021-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0003_auto_20210406_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
